version: 2

run:
  timeout: 3m
  tests: true
  skip-dirs:
    - internal/database/sqlc

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosimple

issues:
  exclude-use-default: false
