version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosimple
  exclusions:
    paths:
          - internal/database/sqlc
    presets:
          - comments

