// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accounts

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID          `json:"id"`
	Phone           *string            `json:"phone"`
	Email           *string            `json:"email"`
	IsPhoneVerified bool               `json:"is_phone_verified"`
	IsEmailVerified bool               `json:"is_email_verified"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
