// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accounts

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (Account, error)
	GetByEmail(ctx context.Context, email *string) (Account, error)
	GetByPhone(ctx context.Context, phone *string) (Account, error)
	UpdateIsEmailVerified(ctx context.Context, arg UpdateIsEmailVerifiedParams) error
	UpdateIsPhoneVerified(ctx context.Context, arg UpdateIsPhoneVerifiedParams) error
}

var _ Querier = (*Queries)(nil)
