// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package accounts

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO accounts (
    id, phone, email
) VALUES (
             $1, $2, $3
         )
RETURNING id, phone, email, is_phone_verified, is_email_verified, created_at, updated_at
`

type CreateParams struct {
	ID    uuid.UUID `json:"id"`
	Phone *string   `json:"phone"`
	Email *string   `json:"email"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Account, error) {
	row := q.db.QueryRow(ctx, create, arg.ID, arg.Phone, arg.Email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.IsPhoneVerified,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, phone, email, is_phone_verified, is_email_verified, created_at, updated_at FROM accounts
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetByEmail(ctx context.Context, email *string) (Account, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.IsPhoneVerified,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByPhone = `-- name: GetByPhone :one
SELECT id, phone, email, is_phone_verified, is_email_verified, created_at, updated_at FROM accounts
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetByPhone(ctx context.Context, phone *string) (Account, error) {
	row := q.db.QueryRow(ctx, getByPhone, phone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.IsPhoneVerified,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIsEmailVerified = `-- name: UpdateIsEmailVerified :exec
UPDATE accounts
set is_email_verified = $2
WHERE id = $1
`

type UpdateIsEmailVerifiedParams struct {
	ID              uuid.UUID `json:"id"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

func (q *Queries) UpdateIsEmailVerified(ctx context.Context, arg UpdateIsEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateIsEmailVerified, arg.ID, arg.IsEmailVerified)
	return err
}

const updateIsPhoneVerified = `-- name: UpdateIsPhoneVerified :exec
UPDATE accounts
set is_phone_verified = $2
WHERE id = $1
`

type UpdateIsPhoneVerifiedParams struct {
	ID              uuid.UUID `json:"id"`
	IsPhoneVerified bool      `json:"is_phone_verified"`
}

func (q *Queries) UpdateIsPhoneVerified(ctx context.Context, arg UpdateIsPhoneVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateIsPhoneVerified, arg.ID, arg.IsPhoneVerified)
	return err
}
