// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package teacinema

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	GetAccountByEmail(ctx context.Context, email *string) (Account, error)
	GetAccountByPhone(ctx context.Context, phone *string) (Account, error)
}

var _ Querier = (*Queries)(nil)
