// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package teacinema

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
}

var _ Querier = (*Queries)(nil)
