// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, phone, email) VALUES ($1, $2, $3)
`

type CreateAccountParams struct {
	ID    uuid.UUID `json:"id"`
	Phone *string   `json:"phone"`
	Email *string   `json:"email"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.ID, arg.Phone, arg.Email)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, phone, email, is_phone_verified, is_email_verified, created_at, updated_at FROM accounts
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email *string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.IsPhoneVerified,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByPhone = `-- name: GetAccountByPhone :one
SELECT id, phone, email, is_phone_verified, is_email_verified, created_at, updated_at FROM accounts
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetAccountByPhone(ctx context.Context, phone *string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPhone, phone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.IsPhoneVerified,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountIsEmailVerified = `-- name: UpdateAccountIsEmailVerified :exec
UPDATE accounts
set is_email_verified = $2
WHERE id = $1
`

type UpdateAccountIsEmailVerifiedParams struct {
	ID              uuid.UUID `json:"id"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

func (q *Queries) UpdateAccountIsEmailVerified(ctx context.Context, arg UpdateAccountIsEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateAccountIsEmailVerified, arg.ID, arg.IsEmailVerified)
	return err
}

const updateAccountIsPhoneVerified = `-- name: UpdateAccountIsPhoneVerified :exec
UPDATE accounts
set is_phone_verified = $2
WHERE id = $1
`

type UpdateAccountIsPhoneVerifiedParams struct {
	ID              uuid.UUID `json:"id"`
	IsPhoneVerified bool      `json:"is_phone_verified"`
}

func (q *Queries) UpdateAccountIsPhoneVerified(ctx context.Context, arg UpdateAccountIsPhoneVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateAccountIsPhoneVerified, arg.ID, arg.IsPhoneVerified)
	return err
}
