// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const accountExistsByEmail = `-- name: AccountExistsByEmail :one
SELECT EXISTS (
    SELECT 1 FROM accounts WHERE email = $1
) AS exists
`

func (q *Queries) AccountExistsByEmail(ctx context.Context, email *string) (bool, error) {
	row := q.db.QueryRow(ctx, accountExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountExistsByPhone = `-- name: AccountExistsByPhone :one
SELECT EXISTS (
    SELECT 1 FROM accounts WHERE phone = $1
) AS exists
`

func (q *Queries) AccountExistsByPhone(ctx context.Context, phone *string) (bool, error) {
	row := q.db.QueryRow(ctx, accountExistsByPhone, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, phone, email, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (phone, email) DO NOTHING
RETURNING id
`

type CreateAccountParams struct {
	ID    uuid.UUID `json:"id"`
	Phone *string   `json:"phone"`
	Email *string   `json:"email"`
	Role  string    `json:"role"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Phone,
		arg.Email,
		arg.Role,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, phone, email, role, created_at, updated_at FROM accounts
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email *string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, phone, email, role, created_at, updated_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByPhone = `-- name: GetAccountByPhone :one
SELECT id, phone, email, role, created_at, updated_at FROM accounts
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetAccountByPhone(ctx context.Context, phone *string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPhone, phone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
