// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, account_id, token_hash, expires_at)
VALUES ($1,$2,$3,$4)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :execrows
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshTokensByAccountID = `-- name: DeleteRefreshTokensByAccountID :exec
DELETE FROM refresh_tokens
WHERE account_id = $1
`

func (q *Queries) DeleteRefreshTokensByAccountID(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByAccountID, accountID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, account_id, token_hash, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
